# default.yaml - Minimal Lima instance template
# Documentation: https://github.com/lima-vm/lima
arch: "x86_64"
images:
  - location: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
    arch: "x86_64"
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000 # replace on first run
mounts:
  - location: "~"
    writable: false
  - location: "/tmp"
    writable: true
ssh:
  localPort: 0
containerd:
  system: true
  user: false
provision:
  - mode: system
    script: |
      #!/bin/bash
      set -euo pipefail
      apt-get update -y
      apt-get install -y ca-certificates curl git
      echo "Provision complete"
message: |
  This is the default Lima template provisioned by Ochairo dotfiles.
  Start with: lima start default