name: CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install bats
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install bats-core
          elif [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y bats
          fi

      - name: Verify bats installation
        run: bats --version

      - name: Run test suite
        run: ./tests/run_tests.sh

      - name: Test dot CLI
        run: |
          ./src/cli/bin/dot --version
          ./src/cli/bin/dot --help

  lint:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./src"
          severity: warning
          ignore_paths: |
            src/components
            src/configs
          ignore_names: |
            *.zsh
            .zshrc
